[package]
name = "cargo-create-library"
version = "0.1.0"
edition = "2021"
description = "Create and import a new library crate in the package"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
